### ISSUE TITLE
Improve server API

### ISSUE THREAD

**Issue by spoenemann** [eclipse/sprotty-server#1]
From theia-ide/sprotty#234:

- [x] add default `type` in `SModelElement`s classes, e.g. `node`  in `SNode`
- [x] add a constant for empty model
- [x] allow to add style classes
- [x] `ITraceProvider.trace()` should retrun the `SModelElement`
- [x] add a template method to handle additional actions in `LanguageAwareDiagramServer#accept`
- [ ] allow to configure `ActionTypeAdapter` using DI (don't use static methods) to add more actions
- [x] `IDiagramGenerator` should take the `Context` as an argument 
- [x] `IDiagramGenerator` should take the `Issues` as an argument 
- [x] add a ServerStatus.Severity `FATAL` that means avoid diagram generation. ERROR could mean we can generate the diagram anyway, e.g. when there are only validation errors 
- [x] add `SIssueMarker` to model

**Comment by JanKoehnlein** [comment]
Not sure about the action adapter anymore. When PRs are through, this can be closed.

**Comment by JanKoehnlein** [comment]
See PRs 
https://github.com/eclipse/sprotty-server/pull/3
https://github.com/eclipse/sprotty-server/pull/4
https://github.com/eclipse/sprotty-server/pull/5
https://github.com/eclipse/sprotty-server/pull/6
