### ISSUE TITLE
lsp4j version number missing in gradle versions

### ISSUE THREAD

**Issue by NiklasRentzCAU** [eclipse/sprotty-server#15]
In sprotty-server/gradle/versions.gradle a version number for lsp4j is missing. That causes the maven central release to list lsp4j version 'null' to be requested as a compile dependency. (see [here.)](https://mvnrepository.com/artifact/org.eclipse.sprotty/org.eclipse.sprotty.xtext/0.6.0)
I don't know, which version of lsp4j you want to depend on, so I will not create an own pull request fixing this issue.

**Comment by JanKoehnlein** [comment]
Fixed with dd5b2622ade1977d5831efbd8152033a10e4ddc7
