### ISSUE TITLE
Improvement: LayoutOptions aligment should be enums rather than String

### ISSUE THREAD

**Issue by kdvolder** [eclipse/sprotty-server#33]
This concerns the Java api of class `org.eclipse.sprotty.LayoutOptions`.

There are some methods there to set options like

```
  public void setVAlign(final String vAlign)
  public void setHAlign(final String hAlign)
```

It is very hard to discover what 'magic' string values are valid parameters for these options. (We had to find/read the code of sprotty typescript for VBoxLayout and HBoxLayout to discover this).

It would be much nicer of you would use enum types here (as is done in other places of the api). Bonus points for adding meaningful documentation to the enum constants, but just having the values explicitly enumerated, would go a long way in helping a new user of the api understand what these methods expect.

**Comment by kdvolder** [comment]
Took a peek at the commits out of curiosity and noticed... This jdoc comment may be a copy-pasting error?

```
                /** 
		 * Elements are aligned on top of each other left to right direction 
		 */
```

I.e. 'left to right direction' was accidentially left behind?

**Comment by JanKoehnlein** [comment]
Fixed it. Thanks for the pointer
