### ISSUE TITLE
OSGi compliant jars

### ISSUE THREAD

**Issue by tomvdbussche** [eclipse/sprotty-server#59]
Are there any plans to make the Sprotty jars OSGi compliant? Since I currently use them within the Eclipse ecosystem I had to create a separate project just to wrap the jars, which is not ideal.

**Comment by spoenemann** [comment]
There's no plan to do that at the moment. What's your use case for that? Do you want a Sprotty view inside Eclipse?

**Comment by tomvdbussche** [comment]
Yes I use it as part of an Eclipse plugin, where I have simple view with a browser backed by an embedded jetty instance.

**Comment by spoenemann** [comment]
We could use the `osgi` Gradle plugin to generate MANIFEST.MF files, similarly to how it's done in LSP4J:
https://github.com/eclipse/lsp4j/blob/master/gradle/manifest-gen.gradle
