### ISSUE TITLE
Build is broken on new Eclipse Jenkins

### ISSUE THREAD

**Issue by spoenemann** [eclipse/sprotty-server#63]
https://ci.eclipse.org/sprotty/job/sprotty-server/job/master/27/console

```
Killed

ERROR: script returned exit code 137
```

**Comment by tortmayr** [comment]
Probably a resource limitation issue. The default resources limit is rather low.
See also: https://wiki.eclipse.org/Jenkins#What_is_killing_my_build.3F_I.27m_using_custom_containers.21

**Comment by JanKoehnlein** [comment]
Fixed by https://github.com/eclipse/sprotty-server/commit/d1207da3368caecd1299b696d53456015401a650
